version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - jarapp
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
        - "9092:9092"
    volumes:
        - "kafka_data:/bitnami"
    environment:
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
        - zookeeper
    networks:
      - jarapp
  mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: docker_cloud
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./docker-cloud.sql:/docker-entrypoint-initdb.d/docker-cloud.sql
    networks:
      - jarapp
  myapp:
    image: dockerxylyjy/docker:1.0.0
    ports:
      - "8888:8888"
    networks:
      - jarapp
    depends_on:
      - kafka
      - mysql
    environment:
      KAFKA_HOST: kafka #kafka-ip
      MYSQL_HOST: mysql #mysql-ip
      DOCKER_HOST: tcp://host.docker.internal:2375 #docker母机连接信息
      
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
  jarapp: